import type { SeedLevel } from './types'

/**
 * A1.1 — 14단원 · 14주 · 주 4회(단원당 4차시) · 누적 어휘 200
 *
 * 대상: 영어를 처음 시작하는 학생.
 * 졸업 요건: "자기소개를 이어진 3–4문장으로 할 수 있다" (Unit 14 말하기)
 *
 * 7단원과 14단원은 통합·복습 단원이라 새 어휘를 넣지 않습니다.
 * 새 어휘는 12개 단원에 나눠 담아 합계 200개가 됩니다.
 */
export const A1_1: SeedLevel = {
  levelCode: 'A1.1',
  units: [
    {
      order: 1,
      title: 'Hello!',
      titleKo: '인사와 이름',
      theme: '만남',
      vocabCount: 17,
      grammar: ['be동사 (I am / You are)', '인칭대명사 주격 I·you', '알파벳 대소문자'],
      vocabulary: ['hello', 'hi', 'good morning', 'good afternoon', 'goodbye', 'name', 'nice', 'meet', 'teacher', 'student', 'friend'],
      canDo: [
        { skill: 'listening', statement: '아침·점심·저녁 인사말을 듣고 언제 쓰는 인사인지 구별할 수 있다.' },
        { skill: 'listening', statement: '상대가 또박또박 말하는 이름의 철자를 듣고 받아 적을 수 있다.' },
        { skill: 'reading', statement: '이름표에 적힌 이름을 소리 내어 읽을 수 있다.' },
        { skill: 'reading', statement: '인사말이 적힌 문장을 읽고 알맞은 상황 그림과 연결할 수 있다.' },
        { skill: 'speaking', statement: '시간대에 맞는 인사말로 먼저 인사할 수 있다.' },
        { skill: 'speaking', statement: '이름을 묻고 답할 수 있다. (What’s your name? — My name is ~)' },
        { skill: 'writing', statement: '자기 이름을 알파벳 대소문자로 바르게 쓸 수 있다.' },
        { skill: 'writing', statement: 'My name is ~ 문장을 첫 글자 대문자와 마침표를 지켜 쓸 수 있다.' },
      ],
    },
    {
      order: 2,
      title: 'Numbers & Age',
      titleKo: '숫자와 나이',
      theme: '나',
      vocabCount: 17,
      grammar: ['How old are you? / I am ~ years old', '숫자 1–20', 'be동사 의문문 기초'],
      vocabulary: ['one', 'two', 'three', 'ten', 'twenty', 'age', 'old', 'how', 'year', 'birthday', 'number'],
      canDo: [
        { skill: 'listening', statement: '1–20 사이의 숫자를 듣고 아라비아 숫자로 받아 적을 수 있다.' },
        { skill: 'listening', statement: '나이를 말하는 문장을 듣고 몇 살인지 알 수 있다.' },
        { skill: 'reading', statement: '숫자 단어(one, two …)를 읽고 아라비아 숫자와 연결할 수 있다.' },
        { skill: 'reading', statement: '이름과 나이가 적힌 소개 카드를 읽고 정보를 찾을 수 있다.' },
        { skill: 'speaking', statement: '나이를 묻고 답할 수 있다.' },
        { skill: 'speaking', statement: '전화번호를 한 자리씩 또박또박 말할 수 있다.' },
        { skill: 'writing', statement: '1–20을 영어 단어로 쓸 수 있다.' },
        { skill: 'writing', statement: 'I am ~ years old. 문장을 쓸 수 있다.' },
      ],
    },
    {
      order: 3,
      title: 'My Family',
      titleKo: '우리 가족',
      theme: '가족',
      vocabCount: 17,
      grammar: ['this / that', '소유격 my·your·his·her', 'be동사 3인칭 (He is / She is)'],
      vocabulary: ['father', 'mother', 'brother', 'sister', 'grandfather', 'grandmother', 'family', 'baby', 'tall', 'kind'],
      canDo: [
        { skill: 'listening', statement: '가족 호칭을 듣고 가계도에서 해당 인물을 찾을 수 있다.' },
        { skill: 'listening', statement: '가족을 소개하는 말을 듣고 가족이 몇 명인지 셀 수 있다.' },
        { skill: 'reading', statement: '가족 소개 글을 읽고 인물과 관계를 연결할 수 있다.' },
        { skill: 'reading', statement: 'his 와 her 를 구별해 누구의 것인지 파악할 수 있다.' },
        { skill: 'speaking', statement: '사진을 보며 This is my ~ 로 가족을 소개할 수 있다.' },
        { skill: 'speaking', statement: '가족 구성원을 세 명 이상 이어서 소개할 수 있다.' },
        { skill: 'writing', statement: 'He is / She is 를 구별해 가족 소개 문장을 쓸 수 있다.' },
        { skill: 'writing', statement: '가족을 소개하는 문장 세 개를 이어서 쓸 수 있다.' },
      ],
    },
    {
      order: 4,
      title: 'My Things',
      titleKo: '내 물건',
      theme: '사물',
      vocabCount: 17,
      grammar: ['명사 복수형', '관사 a / an', 'What’s this?'],
      vocabulary: ['pen', 'pencil', 'book', 'notebook', 'eraser', 'ruler', 'bag', 'desk', 'chair', 'key'],
      canDo: [
        { skill: 'listening', statement: '물건 이름을 듣고 여러 그림 중에서 고를 수 있다.' },
        { skill: 'listening', statement: '단수와 복수를 듣고 한 개인지 여러 개인지 구별할 수 있다.' },
        { skill: 'reading', statement: '물건 목록을 읽고 각각 몇 개인지 파악할 수 있다.' },
        { skill: 'reading', statement: 'a 와 an 이 알맞게 쓰였는지 찾아낼 수 있다.' },
        { skill: 'speaking', statement: '물건을 가리키며 What’s this? 로 묻고 답할 수 있다.' },
        { skill: 'speaking', statement: '자기 가방 속 물건을 세 가지 이상 말할 수 있다.' },
        { skill: 'writing', statement: '명사의 복수형을 규칙에 맞게 쓸 수 있다.' },
        { skill: 'writing', statement: 'It’s a ~ / They are ~ 문장을 구별해 쓸 수 있다.' },
      ],
    },
    {
      order: 5,
      title: 'Colors & Shapes',
      titleKo: '색깔과 모양',
      theme: '묘사',
      vocabCount: 17,
      grammar: ['형용사 + 명사 어순', 'It is + 형용사', '형용사 나열'],
      vocabulary: ['red', 'blue', 'yellow', 'green', 'black', 'white', 'circle', 'square', 'big', 'small', 'long'],
      canDo: [
        { skill: 'listening', statement: '색깔 이름을 듣고 해당 색을 고를 수 있다.' },
        { skill: 'listening', statement: '색과 크기를 함께 설명하는 말을 듣고 알맞은 그림을 찾을 수 있다.' },
        { skill: 'reading', statement: '색깔·모양 단어를 읽고 그림과 연결할 수 있다.' },
        { skill: 'reading', statement: '사물을 묘사한 짧은 문장을 읽고 알맞은 그림을 고를 수 있다.' },
        { skill: 'speaking', statement: '사물의 색과 크기를 함께 말할 수 있다. (It’s a big red ball.)' },
        { skill: 'speaking', statement: '좋아하는 색을 말하고 그 색의 물건을 하나 들 수 있다.' },
        { skill: 'writing', statement: '형용사와 명사의 순서를 지켜 문장을 쓸 수 있다.' },
        { skill: 'writing', statement: '사물 두 개를 색과 크기로 묘사하는 문장을 쓸 수 있다.' },
      ],
    },
    {
      order: 6,
      title: 'My Classroom',
      titleKo: '우리 교실',
      theme: '학교',
      vocabCount: 17,
      grammar: ['There is / There are', 'some / many 기초'],
      vocabulary: ['classroom', 'board', 'window', 'door', 'clock', 'map', 'picture', 'computer', 'wall', 'floor'],
      canDo: [
        { skill: 'listening', statement: '교실 사물의 이름을 듣고 교실에서 찾을 수 있다.' },
        { skill: 'listening', statement: 'There is 와 There are 를 듣고 하나인지 여럿인지 구별할 수 있다.' },
        { skill: 'reading', statement: '교실을 설명한 글을 읽고 없는 물건을 찾아낼 수 있다.' },
        { skill: 'reading', statement: 'There is/are 문장을 읽고 사물의 개수를 파악할 수 있다.' },
        { skill: 'speaking', statement: '교실에 무엇이 있는지 There is/are 로 말할 수 있다.' },
        { skill: 'speaking', statement: '교실 사물 다섯 가지를 이어서 말할 수 있다.' },
        { skill: 'writing', statement: 'There is 와 There are 를 구별해 쓸 수 있다.' },
        { skill: 'writing', statement: '교실을 설명하는 문장 세 개를 쓸 수 있다.' },
      ],
    },
    {
      order: 7,
      title: 'Review 1',
      titleKo: '중간 통합',
      theme: '복습·점검',
      vocabCount: 0,
      isReview: true,
      grammar: ['1–6단원 통합'],
      vocabulary: [],
      canDo: [
        { skill: 'listening', statement: '1–6단원 표현이 섞인 짧은 대화를 듣고 이름·나이·물건을 파악할 수 있다.' },
        { skill: 'listening', statement: '들은 정보를 표에 나누어 정리할 수 있다.' },
        { skill: 'reading', statement: '배운 어휘로 쓰인 짧은 소개 글을 읽고 내용을 파악할 수 있다.' },
        { skill: 'reading', statement: '글을 읽고 주어진 문장의 참·거짓을 판단할 수 있다.' },
        { skill: 'speaking', statement: '이름·나이·가족·물건을 섞어 자기를 소개할 수 있다.' },
        { skill: 'speaking', statement: '짝에게 배운 표현으로 세 가지 이상 질문할 수 있다.' },
        { skill: 'writing', statement: '배운 문형으로 자기소개 문장 다섯 개를 쓸 수 있다.' },
        { skill: 'writing', statement: '첫 글자 대문자와 마침표를 지켜 쓸 수 있다.' },
      ],
    },
    {
      order: 8,
      title: 'Where Is It?',
      titleKo: '어디에 있나요',
      theme: '위치',
      vocabCount: 17,
      grammar: ['장소 전치사 in / on / under / next to', 'Where is ~?'],
      vocabulary: ['in', 'on', 'under', 'next to', 'behind', 'room', 'table', 'bed', 'kitchen', 'where'],
      canDo: [
        { skill: 'listening', statement: '위치를 설명하는 말을 듣고 물건을 찾을 수 있다.' },
        { skill: 'listening', statement: '전치사를 듣고 알맞은 위치의 그림을 고를 수 있다.' },
        { skill: 'reading', statement: '위치를 나타낸 문장을 읽고 그림과 연결할 수 있다.' },
        { skill: 'reading', statement: '방을 설명한 글을 읽고 각 물건이 어디 있는지 파악할 수 있다.' },
        { skill: 'speaking', statement: '물건의 위치를 묻고 답할 수 있다.' },
        { skill: 'speaking', statement: '자기 방에 무엇이 어디 있는지 세 가지 이상 말할 수 있다.' },
        { skill: 'writing', statement: '전치사를 써서 위치를 나타내는 문장을 쓸 수 있다.' },
        { skill: 'writing', statement: '그림을 보고 위치를 설명하는 문장 세 개를 쓸 수 있다.' },
      ],
    },
    {
      order: 9,
      title: 'Food I Like',
      titleKo: '좋아하는 음식',
      theme: '음식',
      vocabCount: 17,
      grammar: ['일반동사 현재형 긍정·부정 (I like / I don’t like)'],
      vocabulary: ['rice', 'bread', 'milk', 'water', 'juice', 'apple', 'egg', 'meat', 'fish', 'cake'],
      canDo: [
        { skill: 'listening', statement: '음식 이름을 듣고 그림에서 고를 수 있다.' },
        { skill: 'listening', statement: '좋아함과 싫어함을 나타내는 말을 듣고 구별할 수 있다.' },
        { skill: 'reading', statement: '음식 이름을 읽고 종류별로 분류할 수 있다.' },
        { skill: 'reading', statement: '좋아하는 음식을 소개한 글에서 원하는 정보를 찾을 수 있다.' },
        { skill: 'speaking', statement: '좋아하는 음식과 싫어하는 음식을 말할 수 있다.' },
        { skill: 'speaking', statement: '짝에게 좋아하는 음식을 묻고 답할 수 있다.' },
        { skill: 'writing', statement: 'I like / I don’t like 문장을 쓸 수 있다.' },
        { skill: 'writing', statement: '좋아하는 음식 세 가지를 문장으로 쓸 수 있다.' },
      ],
    },
    {
      order: 10,
      title: 'Animals',
      titleKo: '동물',
      theme: '동물',
      vocabCount: 17,
      grammar: ['일반동사 의문문 Do you like ~?', 'Yes, I do. / No, I don’t.'],
      vocabulary: ['dog', 'cat', 'bird', 'rabbit', 'horse', 'lion', 'tiger', 'elephant', 'monkey', 'pet'],
      canDo: [
        { skill: 'listening', statement: '동물 이름을 듣고 그림에서 고를 수 있다.' },
        { skill: 'listening', statement: 'Do you like ~? 질문과 대답을 듣고 좋아하는지 알 수 있다.' },
        { skill: 'reading', statement: '동물을 묘사한 짧은 글을 읽고 어떤 동물인지 맞힐 수 있다.' },
        { skill: 'reading', statement: '질문과 대답을 읽고 알맞게 짝지을 수 있다.' },
        { skill: 'speaking', statement: 'Do you like ~? 로 묻고 Yes/No 로 답할 수 있다.' },
        { skill: 'speaking', statement: '좋아하는 동물을 색과 크기를 넣어 소개할 수 있다.' },
        { skill: 'writing', statement: 'Do you like ~? 형태의 의문문을 쓸 수 있다.' },
        { skill: 'writing', statement: '좋아하는 동물을 소개하는 문장 세 개를 쓸 수 있다.' },
      ],
    },
    {
      order: 11,
      title: 'My Day',
      titleKo: '하루 일과',
      theme: '일상',
      vocabCount: 17,
      grammar: ['현재시제 일과 표현', '시각 말하기 (at seven)', '시간 전치사 at'],
      vocabulary: ['get up', 'wash', 'eat', 'go', 'study', 'play', 'sleep', 'morning', 'evening', 'o’clock'],
      canDo: [
        { skill: 'listening', statement: '시각을 듣고 시계 그림과 연결할 수 있다.' },
        { skill: 'listening', statement: '하루 일과를 듣고 일어난 순서대로 정리할 수 있다.' },
        { skill: 'reading', statement: '일과표를 읽고 시간과 활동을 연결할 수 있다.' },
        { skill: 'reading', statement: '하루를 설명한 글을 읽고 순서를 파악할 수 있다.' },
        { skill: 'speaking', statement: '자기 하루 일과를 시간과 함께 세 가지 이상 말할 수 있다.' },
        { skill: 'speaking', statement: '몇 시에 무엇을 하는지 묻고 답할 수 있다.' },
        { skill: 'writing', statement: 'I get up at seven. 같은 시각 표현 문장을 쓸 수 있다.' },
        { skill: 'writing', statement: '자기 하루를 네 문장으로 순서대로 쓸 수 있다.' },
      ],
    },
    {
      order: 12,
      title: 'Can You?',
      titleKo: '할 수 있는 것',
      theme: '능력',
      vocabCount: 16,
      grammar: ['can / can’t', 'Can you ~? 의문문'],
      vocabulary: ['swim', 'ride', 'sing', 'dance', 'draw', 'cook', 'read', 'write', 'speak', 'well'],
      canDo: [
        { skill: 'listening', statement: 'can 과 can’t 를 듣고 구별할 수 있다.' },
        { skill: 'listening', statement: '누가 무엇을 할 수 있는지 듣고 표에 표시할 수 있다.' },
        { skill: 'reading', statement: 'can 문장을 읽고 가능한지 아닌지 판단할 수 있다.' },
        { skill: 'reading', statement: '인물 소개 글을 읽고 그 사람이 할 수 있는 일을 찾을 수 있다.' },
        { skill: 'speaking', statement: '자기가 할 수 있는 것과 할 수 없는 것을 말할 수 있다.' },
        { skill: 'speaking', statement: 'Can you ~? 로 묻고 답할 수 있다.' },
        { skill: 'writing', statement: 'can 과 can’t 문장을 구별해 쓸 수 있다.' },
        { skill: 'writing', statement: '자기가 할 수 있는 일 세 가지를 문장으로 쓸 수 있다.' },
      ],
    },
    {
      order: 13,
      title: 'My Friends',
      titleKo: '내 친구',
      theme: '관계',
      vocabCount: 14,
      grammar: ['3인칭 단수 현재형 (He likes / She has)', '인물 묘사 형용사'],
      vocabulary: ['friend', 'classmate', 'funny', 'smart', 'quiet', 'have', 'has', 'together', 'best', 'know'],
      canDo: [
        { skill: 'listening', statement: '친구를 소개하는 말을 듣고 그 친구의 특징을 파악할 수 있다.' },
        { skill: 'listening', statement: 'He 와 She 를 듣고 누구를 가리키는지 알 수 있다.' },
        { skill: 'reading', statement: '친구 소개 글을 읽고 인물의 특징을 정리할 수 있다.' },
        { skill: 'reading', statement: '3인칭 단수 문장을 읽고 누구에 대한 이야기인지 찾을 수 있다.' },
        { skill: 'speaking', statement: '친구를 이름·나이·좋아하는 것과 함께 소개할 수 있다.' },
        { skill: 'speaking', statement: 'He likes ~ / She has ~ 형태로 말할 수 있다.' },
        { skill: 'writing', statement: '3인칭 단수에 -s 를 붙여 문장을 쓸 수 있다.' },
        { skill: 'writing', statement: '친구를 소개하는 문장 네 개를 쓸 수 있다.' },
      ],
    },
    {
      order: 14,
      title: 'About Me',
      titleKo: '나를 소개해요',
      theme: '통합·발표',
      vocabCount: 0,
      isReview: true,
      grammar: ['1–13단원 통합'],
      vocabulary: [],
      canDo: [
        { skill: 'listening', statement: '또래의 자기소개 발표를 듣고 핵심 정보를 파악할 수 있다.' },
        { skill: 'listening', statement: '발표를 듣고 그 사람에게 물어볼 질문 한 가지를 만들 수 있다.' },
        { skill: 'reading', statement: '자기소개 글을 읽고 인물 정보를 표로 정리할 수 있다.' },
        { skill: 'reading', statement: '여러 사람의 소개 글을 읽고 공통점을 찾을 수 있다.' },
        { skill: 'speaking', statement: '자기소개를 이어진 3–4문장으로 할 수 있다.' },
        { skill: 'speaking', statement: '발표 후 간단한 질문에 답할 수 있다.' },
        { skill: 'writing', statement: '자기소개 글을 다섯 문장 이상으로 쓸 수 있다.' },
        { skill: 'writing', statement: '대문자·마침표·띄어쓰기를 지켜 글을 쓸 수 있다.' },
      ],
    },
  ],
}

/** 지금까지 원안이 작성된 레벨 */
export const SEED_LEVELS = [A1_1]

export function seedFor(levelCode: string) {
  return SEED_LEVELS.find((l) => l.levelCode === levelCode)
}
