import type { SeedLevel } from './types'

/**
 * A1.1 — 14단원 · 14주 · 주 4회(단원당 4차시)
 *
 * 대상: 영어를 처음 시작하는 학생.
 * 졸업 요건: "자기소개를 이어진 3–4문장으로 할 수 있다" (Unit 14 말하기)
 *
 * 어휘는 뒤로 갈수록 늘립니다 (12 → 21). 처음에는 알파벳과 소리에 적응할 시간이
 * 필요하고, 학기 후반에는 앞 단원 어휘가 받쳐 주므로 더 많이 소화할 수 있습니다.
 * 7단원과 14단원은 통합·복습이라 새 어휘가 없습니다. 합계 200개.
 */
export const A1_1: SeedLevel = {
  levelCode: 'A1.1',
  units: [
    {
      order: 1,
      title: 'Hello!',
      titleKo: '인사와 이름',
      theme: '만남',
      grammar: [
        { title: 'be동사 (I am / You are)', canDo: '자기를 소개하는 문장을 만들 수 있다.' },
        { title: '인칭대명사 주격 I · you', canDo: '나와 상대를 가리켜 말할 수 있다.' },
        { title: '알파벳 대소문자', canDo: '이름을 바르게 표기할 수 있다.' },
      ],
      vocabulary: [
        { en: 'hello', ko: '안녕하세요', pos: 'phrase', type: 'idiom' },
        { en: 'hi', ko: '안녕', pos: 'phrase', type: 'idiom' },
        { en: 'good morning', ko: '좋은 아침', pos: 'phrase', type: 'collocation' },
        { en: 'good afternoon', ko: '안녕하세요 (오후 인사)', pos: 'phrase', type: 'collocation' },
        { en: 'good evening', ko: '안녕하세요 (저녁 인사)', pos: 'phrase', type: 'collocation' },
        { en: 'goodbye', ko: '안녕히 가세요', pos: 'phrase', type: 'idiom' },
        { en: 'name', ko: '이름', pos: 'noun' },
        { en: 'nice', ko: '좋은, 반가운', pos: 'adjective' },
        { en: 'meet', ko: '만나다', pos: 'verb' },
        { en: 'teacher', ko: '선생님', pos: 'noun' },
        { en: 'student', ko: '학생', pos: 'noun' },
        { en: 'please', ko: '부탁합니다', pos: 'adverb' },
      ],
      canDo: [
        { skill: 'listening', statement: '아침·점심·저녁 인사말을 듣고 언제 쓰는 인사인지 구별할 수 있다.' },
        { skill: 'listening', statement: '상대가 또박또박 말하는 이름의 철자를 듣고 받아 적을 수 있다.' },
        { skill: 'reading', statement: '이름표에 적힌 이름을 소리 내어 읽을 수 있다.' },
        { skill: 'reading', statement: '인사말이 적힌 문장을 읽고 알맞은 상황 그림과 연결할 수 있다.' },
        { skill: 'speaking', statement: '시간대에 맞는 인사말로 먼저 인사할 수 있다.' },
        { skill: 'speaking', statement: '이름을 묻고 답할 수 있다. (What’s your name? — My name is ~)' },
        { skill: 'writing', statement: '자기 이름을 알파벳 대소문자로 바르게 쓸 수 있다.' },
        { skill: 'writing', statement: 'My name is ~ 문장을 첫 글자 대문자와 마침표를 지켜 쓸 수 있다.' },
      ],
    },

    {
      order: 2,
      title: 'Numbers & Age',
      titleKo: '숫자와 나이',
      theme: '나',
      grammar: [
        { title: '숫자 1–20', canDo: '스무 개까지 수를 세어 말할 수 있다.' },
        { title: 'How old are you? / I am ~ years old', canDo: '나이를 묻고 답할 수 있다.' },
      ],
      vocabulary: [
        { en: 'one', ko: '하나', pos: 'noun' },
        { en: 'two', ko: '둘', pos: 'noun' },
        { en: 'three', ko: '셋', pos: 'noun' },
        { en: 'four', ko: '넷', pos: 'noun' },
        { en: 'five', ko: '다섯', pos: 'noun' },
        { en: 'six', ko: '여섯', pos: 'noun' },
        { en: 'seven', ko: '일곱', pos: 'noun' },
        { en: 'eight', ko: '여덟', pos: 'noun' },
        { en: 'nine', ko: '아홉', pos: 'noun' },
        { en: 'ten', ko: '열', pos: 'noun' },
        { en: 'old', ko: '나이가 ~인, 오래된', pos: 'adjective' },
        { en: 'year', ko: '해, 년', pos: 'noun' },
        { en: 'birthday', ko: '생일', pos: 'noun' },
      ],
      canDo: [
        { skill: 'listening', statement: '1–20 사이의 숫자를 듣고 아라비아 숫자로 받아 적을 수 있다.' },
        { skill: 'listening', statement: '나이를 말하는 문장을 듣고 몇 살인지 알 수 있다.' },
        { skill: 'reading', statement: '숫자 단어(one, two …)를 읽고 아라비아 숫자와 연결할 수 있다.' },
        { skill: 'reading', statement: '이름과 나이가 적힌 소개 카드를 읽고 정보를 찾을 수 있다.' },
        { skill: 'speaking', statement: '나이를 묻고 답할 수 있다.' },
        { skill: 'speaking', statement: '전화번호를 한 자리씩 또박또박 말할 수 있다.' },
        { skill: 'writing', statement: '1–20을 영어 단어로 쓸 수 있다.' },
        { skill: 'writing', statement: 'I am ~ years old. 문장을 쓸 수 있다.' },
      ],
    },

    {
      order: 3,
      title: 'My Family',
      titleKo: '우리 가족',
      theme: '가족',
      grammar: [
        { title: 'this / that', canDo: '가까운 것과 먼 것을 가리켜 말할 수 있다.' },
        { title: '소유격 my · your · his · her', canDo: '누구의 것인지 밝혀 말할 수 있다.' },
        { title: 'be동사 3인칭 (He is / She is)', canDo: '제3자를 소개할 수 있다.' },
      ],
      vocabulary: [
        { en: 'father', ko: '아버지', pos: 'noun' },
        { en: 'mother', ko: '어머니', pos: 'noun' },
        { en: 'brother', ko: '형, 오빠, 남동생', pos: 'noun' },
        { en: 'sister', ko: '누나, 언니, 여동생', pos: 'noun' },
        { en: 'grandfather', ko: '할아버지', pos: 'noun' },
        { en: 'grandmother', ko: '할머니', pos: 'noun' },
        { en: 'parents', ko: '부모님', pos: 'noun' },
        { en: 'family', ko: '가족', pos: 'noun' },
        { en: 'baby', ko: '아기', pos: 'noun' },
        { en: 'tall', ko: '키가 큰', pos: 'adjective' },
        { en: 'kind', ko: '친절한', pos: 'adjective' },
        { en: 'this', ko: '이것, 이 사람', pos: 'pronoun' },
        { en: 'that', ko: '저것, 저 사람', pos: 'pronoun' },
        { en: 'love', ko: '사랑하다', pos: 'verb' },
      ],
      canDo: [
        { skill: 'listening', statement: '가족 호칭을 듣고 가계도에서 해당 인물을 찾을 수 있다.' },
        { skill: 'listening', statement: '가족을 소개하는 말을 듣고 가족이 몇 명인지 셀 수 있다.' },
        { skill: 'reading', statement: '가족 소개 글을 읽고 인물과 관계를 연결할 수 있다.' },
        { skill: 'reading', statement: 'his 와 her 를 구별해 누구의 것인지 파악할 수 있다.' },
        { skill: 'speaking', statement: '사진을 보며 This is my ~ 로 가족을 소개할 수 있다.' },
        { skill: 'speaking', statement: '가족 구성원을 세 명 이상 이어서 소개할 수 있다.' },
        { skill: 'writing', statement: 'He is / She is 를 구별해 가족 소개 문장을 쓸 수 있다.' },
        { skill: 'writing', statement: '가족을 소개하는 문장 세 개를 이어서 쓸 수 있다.' },
      ],
    },

    {
      order: 4,
      title: 'My Things',
      titleKo: '내 물건',
      theme: '사물',
      grammar: [
        { title: '명사 복수형', canDo: '하나와 여럿을 구별해 말할 수 있다.' },
        { title: '관사 a / an', canDo: '셀 수 있는 명사 앞에 관사를 붙여 말할 수 있다.' },
        { title: 'What’s this? / It’s a ~', canDo: '사물의 이름을 묻고 답할 수 있다.' },
      ],
      vocabulary: [
        { en: 'pen', ko: '펜', pos: 'noun' },
        { en: 'pencil', ko: '연필', pos: 'noun' },
        { en: 'book', ko: '책', pos: 'noun' },
        { en: 'notebook', ko: '공책', pos: 'noun' },
        { en: 'eraser', ko: '지우개', pos: 'noun' },
        { en: 'ruler', ko: '자', pos: 'noun' },
        { en: 'bag', ko: '가방', pos: 'noun' },
        { en: 'desk', ko: '책상', pos: 'noun' },
        { en: 'chair', ko: '의자', pos: 'noun' },
        { en: 'key', ko: '열쇠', pos: 'noun' },
        { en: 'cup', ko: '컵', pos: 'noun' },
        { en: 'box', ko: '상자', pos: 'noun' },
        { en: 'thing', ko: '물건, 것', pos: 'noun' },
        { en: 'have', ko: '가지다', pos: 'verb' },
        { en: 'my', ko: '나의', pos: 'determiner' },
      ],
      canDo: [
        { skill: 'listening', statement: '물건 이름을 듣고 여러 그림 중에서 고를 수 있다.' },
        { skill: 'listening', statement: '단수와 복수를 듣고 한 개인지 여러 개인지 구별할 수 있다.' },
        { skill: 'reading', statement: '물건 목록을 읽고 각각 몇 개인지 파악할 수 있다.' },
        { skill: 'reading', statement: 'a 와 an 이 알맞게 쓰였는지 찾아낼 수 있다.' },
        { skill: 'speaking', statement: '물건을 가리키며 What’s this? 로 묻고 답할 수 있다.' },
        { skill: 'speaking', statement: '자기 가방 속 물건을 세 가지 이상 말할 수 있다.' },
        { skill: 'writing', statement: '명사의 복수형을 규칙에 맞게 쓸 수 있다.' },
        { skill: 'writing', statement: 'It’s a ~ / They are ~ 문장을 구별해 쓸 수 있다.' },
      ],
    },

    {
      order: 5,
      title: 'Colors & Shapes',
      titleKo: '색깔과 모양',
      theme: '묘사',
      grammar: [
        { title: '형용사 + 명사 어순', canDo: '사물을 꾸며 말할 수 있다.' },
        { title: 'It is + 형용사', canDo: '사물의 성질을 말할 수 있다.' },
      ],
      vocabulary: [
        { en: 'red', ko: '빨강', pos: 'adjective' },
        { en: 'blue', ko: '파랑', pos: 'adjective' },
        { en: 'yellow', ko: '노랑', pos: 'adjective' },
        { en: 'green', ko: '초록', pos: 'adjective' },
        { en: 'black', ko: '검정', pos: 'adjective' },
        { en: 'white', ko: '하양', pos: 'adjective' },
        { en: 'orange', ko: '주황', pos: 'adjective' },
        { en: 'pink', ko: '분홍', pos: 'adjective' },
        { en: 'brown', ko: '갈색', pos: 'adjective' },
        { en: 'circle', ko: '원', pos: 'noun' },
        { en: 'square', ko: '정사각형', pos: 'noun' },
        { en: 'triangle', ko: '삼각형', pos: 'noun' },
        { en: 'big', ko: '큰', pos: 'adjective' },
        { en: 'small', ko: '작은', pos: 'adjective' },
        { en: 'long', ko: '긴', pos: 'adjective' },
        { en: 'color', ko: '색깔', pos: 'noun' },
      ],
      canDo: [
        { skill: 'listening', statement: '색깔 이름을 듣고 해당 색을 고를 수 있다.' },
        { skill: 'listening', statement: '색과 크기를 함께 설명하는 말을 듣고 알맞은 그림을 찾을 수 있다.' },
        { skill: 'reading', statement: '색깔·모양 단어를 읽고 그림과 연결할 수 있다.' },
        { skill: 'reading', statement: '사물을 묘사한 짧은 문장을 읽고 알맞은 그림을 고를 수 있다.' },
        { skill: 'speaking', statement: '사물의 색과 크기를 함께 말할 수 있다. (It’s a big red ball.)' },
        { skill: 'speaking', statement: '좋아하는 색을 말하고 그 색의 물건을 하나 들 수 있다.' },
        { skill: 'writing', statement: '형용사와 명사의 순서를 지켜 문장을 쓸 수 있다.' },
        { skill: 'writing', statement: '사물 두 개를 색과 크기로 묘사하는 문장을 쓸 수 있다.' },
      ],
    },

    {
      order: 6,
      title: 'My Classroom',
      titleKo: '우리 교실',
      theme: '학교',
      grammar: [
        { title: 'There is / There are', canDo: '무엇이 있는지 말할 수 있다.' },
        { title: 'some / many', canDo: '막연한 수량을 말할 수 있다.' },
      ],
      vocabulary: [
        { en: 'classroom', ko: '교실', pos: 'noun' },
        { en: 'board', ko: '칠판', pos: 'noun' },
        { en: 'window', ko: '창문', pos: 'noun' },
        { en: 'door', ko: '문', pos: 'noun' },
        { en: 'clock', ko: '시계', pos: 'noun' },
        { en: 'map', ko: '지도', pos: 'noun' },
        { en: 'picture', ko: '그림, 사진', pos: 'noun' },
        { en: 'computer', ko: '컴퓨터', pos: 'noun' },
        { en: 'wall', ko: '벽', pos: 'noun' },
        { en: 'floor', ko: '바닥', pos: 'noun' },
        { en: 'light', ko: '전등, 빛', pos: 'noun' },
        { en: 'school', ko: '학교', pos: 'noun' },
        { en: 'class', ko: '반, 수업', pos: 'noun' },
        { en: 'many', ko: '많은', pos: 'determiner' },
        { en: 'some', ko: '몇몇의', pos: 'determiner' },
        { en: 'there', ko: '거기에', pos: 'adverb' },
        { en: 'new', ko: '새로운', pos: 'adjective' },
      ],
      canDo: [
        { skill: 'listening', statement: '교실 사물의 이름을 듣고 교실에서 찾을 수 있다.' },
        { skill: 'listening', statement: 'There is 와 There are 를 듣고 하나인지 여럿인지 구별할 수 있다.' },
        { skill: 'reading', statement: '교실을 설명한 글을 읽고 없는 물건을 찾아낼 수 있다.' },
        { skill: 'reading', statement: 'There is/are 문장을 읽고 사물의 개수를 파악할 수 있다.' },
        { skill: 'speaking', statement: '교실에 무엇이 있는지 There is/are 로 말할 수 있다.' },
        { skill: 'speaking', statement: '교실 사물 다섯 가지를 이어서 말할 수 있다.' },
        { skill: 'writing', statement: 'There is 와 There are 를 구별해 쓸 수 있다.' },
        { skill: 'writing', statement: '교실을 설명하는 문장 세 개를 쓸 수 있다.' },
      ],
    },

    {
      order: 7,
      title: 'Review 1',
      titleKo: '중간 통합',
      theme: '복습·점검',
      isReview: true,
      grammar: [{ title: '1–6단원 통합' }],
      vocabulary: [],
      canDo: [
        { skill: 'listening', statement: '1–6단원 표현이 섞인 짧은 대화를 듣고 이름·나이·물건을 파악할 수 있다.' },
        { skill: 'listening', statement: '들은 정보를 표에 나누어 정리할 수 있다.' },
        { skill: 'reading', statement: '배운 어휘로 쓰인 짧은 소개 글을 읽고 내용을 파악할 수 있다.' },
        { skill: 'reading', statement: '글을 읽고 주어진 문장의 참·거짓을 판단할 수 있다.' },
        { skill: 'speaking', statement: '이름·나이·가족·물건을 섞어 자기를 소개할 수 있다.' },
        { skill: 'speaking', statement: '짝에게 배운 표현으로 세 가지 이상 질문할 수 있다.' },
        { skill: 'writing', statement: '배운 문형으로 자기소개 문장 다섯 개를 쓸 수 있다.' },
        { skill: 'writing', statement: '첫 글자 대문자와 마침표를 지켜 쓸 수 있다.' },
      ],
    },

    {
      order: 8,
      title: 'Where Is It?',
      titleKo: '어디에 있나요',
      theme: '위치',
      grammar: [
        { title: '장소 전치사 in / on / under / next to', canDo: '위치를 나타내어 말할 수 있다.' },
        { title: 'Where is ~?', canDo: '물건이 어디 있는지 물을 수 있다.' },
      ],
      vocabulary: [
        { en: 'in', ko: '~ 안에', pos: 'preposition' },
        { en: 'on', ko: '~ 위에', pos: 'preposition' },
        { en: 'under', ko: '~ 아래에', pos: 'preposition' },
        { en: 'next to', ko: '~ 옆에', pos: 'preposition', type: 'collocation' },
        { en: 'behind', ko: '~ 뒤에', pos: 'preposition' },
        { en: 'in front of', ko: '~ 앞에', pos: 'preposition', type: 'collocation' },
        { en: 'room', ko: '방', pos: 'noun' },
        { en: 'table', ko: '탁자', pos: 'noun' },
        { en: 'bed', ko: '침대', pos: 'noun' },
        { en: 'sofa', ko: '소파', pos: 'noun' },
        { en: 'kitchen', ko: '부엌', pos: 'noun' },
        { en: 'house', ko: '집', pos: 'noun' },
        { en: 'where', ko: '어디에', pos: 'adverb' },
        { en: 'here', ko: '여기에', pos: 'adverb' },
        { en: 'put', ko: '놓다', pos: 'verb' },
        { en: 'find', ko: '찾다', pos: 'verb' },
        { en: 'look', ko: '보다', pos: 'verb' },
      ],
      canDo: [
        { skill: 'listening', statement: '위치를 설명하는 말을 듣고 물건을 찾을 수 있다.' },
        { skill: 'listening', statement: '전치사를 듣고 알맞은 위치의 그림을 고를 수 있다.' },
        { skill: 'reading', statement: '위치를 나타낸 문장을 읽고 그림과 연결할 수 있다.' },
        { skill: 'reading', statement: '방을 설명한 글을 읽고 각 물건이 어디 있는지 파악할 수 있다.' },
        { skill: 'speaking', statement: '물건의 위치를 묻고 답할 수 있다.' },
        { skill: 'speaking', statement: '자기 방에 무엇이 어디 있는지 세 가지 이상 말할 수 있다.' },
        { skill: 'writing', statement: '전치사를 써서 위치를 나타내는 문장을 쓸 수 있다.' },
        { skill: 'writing', statement: '그림을 보고 위치를 설명하는 문장 세 개를 쓸 수 있다.' },
      ],
    },

    {
      order: 9,
      title: 'Food I Like',
      titleKo: '좋아하는 음식',
      theme: '음식',
      grammar: [
        { title: '일반동사 현재형 긍정 (I like ~)', canDo: '좋아하는 것을 말할 수 있다.' },
        { title: '일반동사 부정 (I don’t like ~)', canDo: '싫어하는 것을 말할 수 있다.' },
      ],
      vocabulary: [
        { en: 'rice', ko: '밥, 쌀', pos: 'noun' },
        { en: 'bread', ko: '빵', pos: 'noun' },
        { en: 'milk', ko: '우유', pos: 'noun' },
        { en: 'water', ko: '물', pos: 'noun' },
        { en: 'juice', ko: '주스', pos: 'noun' },
        { en: 'apple', ko: '사과', pos: 'noun' },
        { en: 'banana', ko: '바나나', pos: 'noun' },
        { en: 'egg', ko: '달걀', pos: 'noun' },
        { en: 'meat', ko: '고기', pos: 'noun' },
        { en: 'fish', ko: '생선', pos: 'noun' },
        { en: 'soup', ko: '국, 수프', pos: 'noun' },
        { en: 'cake', ko: '케이크', pos: 'noun' },
        { en: 'food', ko: '음식', pos: 'noun' },
        { en: 'eat', ko: '먹다', pos: 'verb' },
        { en: 'drink', ko: '마시다', pos: 'verb' },
        { en: 'like', ko: '좋아하다', pos: 'verb' },
        { en: 'want', ko: '원하다', pos: 'verb' },
        { en: 'hungry', ko: '배고픈', pos: 'adjective' },
      ],
      canDo: [
        { skill: 'listening', statement: '음식 이름을 듣고 그림에서 고를 수 있다.' },
        { skill: 'listening', statement: '좋아함과 싫어함을 나타내는 말을 듣고 구별할 수 있다.' },
        { skill: 'reading', statement: '음식 이름을 읽고 종류별로 분류할 수 있다.' },
        { skill: 'reading', statement: '좋아하는 음식을 소개한 글에서 원하는 정보를 찾을 수 있다.' },
        { skill: 'speaking', statement: '좋아하는 음식과 싫어하는 음식을 말할 수 있다.' },
        { skill: 'speaking', statement: '짝에게 좋아하는 음식을 묻고 답할 수 있다.' },
        { skill: 'writing', statement: 'I like / I don’t like 문장을 쓸 수 있다.' },
        { skill: 'writing', statement: '좋아하는 음식 세 가지를 문장으로 쓸 수 있다.' },
      ],
    },

    {
      order: 10,
      title: 'Animals',
      titleKo: '동물',
      theme: '동물',
      grammar: [
        { title: '일반동사 의문문 (Do you like ~?)', canDo: '상대의 취향을 물을 수 있다.' },
        { title: 'Yes, I do. / No, I don’t.', canDo: '짧은 대답으로 응답할 수 있다.' },
      ],
      vocabulary: [
        { en: 'dog', ko: '개', pos: 'noun' },
        { en: 'cat', ko: '고양이', pos: 'noun' },
        { en: 'bird', ko: '새', pos: 'noun' },
        { en: 'rabbit', ko: '토끼', pos: 'noun' },
        { en: 'horse', ko: '말', pos: 'noun' },
        { en: 'cow', ko: '소', pos: 'noun' },
        { en: 'pig', ko: '돼지', pos: 'noun' },
        { en: 'lion', ko: '사자', pos: 'noun' },
        { en: 'tiger', ko: '호랑이', pos: 'noun' },
        { en: 'elephant', ko: '코끼리', pos: 'noun' },
        { en: 'monkey', ko: '원숭이', pos: 'noun' },
        { en: 'animal', ko: '동물', pos: 'noun' },
        { en: 'pet', ko: '반려동물', pos: 'noun' },
        { en: 'tail', ko: '꼬리', pos: 'noun' },
        { en: 'run', ko: '달리다', pos: 'verb' },
        { en: 'jump', ko: '뛰다', pos: 'verb' },
        { en: 'fly', ko: '날다', pos: 'verb' },
        { en: 'cute', ko: '귀여운', pos: 'adjective' },
      ],
      canDo: [
        { skill: 'listening', statement: '동물 이름을 듣고 그림에서 고를 수 있다.' },
        { skill: 'listening', statement: 'Do you like ~? 질문과 대답을 듣고 좋아하는지 알 수 있다.' },
        { skill: 'reading', statement: '동물을 묘사한 짧은 글을 읽고 어떤 동물인지 맞힐 수 있다.' },
        { skill: 'reading', statement: '질문과 대답을 읽고 알맞게 짝지을 수 있다.' },
        { skill: 'speaking', statement: 'Do you like ~? 로 묻고 Yes/No 로 답할 수 있다.' },
        { skill: 'speaking', statement: '좋아하는 동물을 색과 크기를 넣어 소개할 수 있다.' },
        { skill: 'writing', statement: 'Do you like ~? 형태의 의문문을 쓸 수 있다.' },
        { skill: 'writing', statement: '좋아하는 동물을 소개하는 문장 세 개를 쓸 수 있다.' },
      ],
    },

    {
      order: 11,
      title: 'My Day',
      titleKo: '하루 일과',
      theme: '일상',
      grammar: [
        { title: '현재시제 일과 표현', canDo: '반복되는 일상을 말할 수 있다.' },
        { title: '시각 말하기 (at seven / o’clock)', canDo: '몇 시에 하는지 말할 수 있다.' },
        { title: '시간 전치사 at', canDo: '시각을 문장에 넣을 수 있다.' },
      ],
      vocabulary: [
        { en: 'get up', ko: '일어나다', pos: 'verb', type: 'phrasal_verb' },
        { en: 'wash', ko: '씻다', pos: 'verb' },
        { en: 'go', ko: '가다', pos: 'verb' },
        { en: 'come', ko: '오다', pos: 'verb' },
        { en: 'study', ko: '공부하다', pos: 'verb' },
        { en: 'play', ko: '놀다', pos: 'verb' },
        { en: 'sleep', ko: '자다', pos: 'verb' },
        { en: 'morning', ko: '아침', pos: 'noun' },
        { en: 'afternoon', ko: '오후', pos: 'noun' },
        { en: 'evening', ko: '저녁', pos: 'noun' },
        { en: 'night', ko: '밤', pos: 'noun' },
        { en: 'day', ko: '날, 하루', pos: 'noun' },
        { en: 'time', ko: '시간', pos: 'noun' },
        { en: 'home', ko: '집', pos: 'noun' },
        { en: 'breakfast', ko: '아침 식사', pos: 'noun' },
        { en: 'lunch', ko: '점심 식사', pos: 'noun' },
        { en: 'dinner', ko: '저녁 식사', pos: 'noun' },
        { en: 'early', ko: '이른, 일찍', pos: 'adjective' },
        { en: 'late', ko: '늦은, 늦게', pos: 'adjective' },
      ],
      canDo: [
        { skill: 'listening', statement: '시각을 듣고 시계 그림과 연결할 수 있다.' },
        { skill: 'listening', statement: '하루 일과를 듣고 일어난 순서대로 정리할 수 있다.' },
        { skill: 'reading', statement: '일과표를 읽고 시간과 활동을 연결할 수 있다.' },
        { skill: 'reading', statement: '하루를 설명한 글을 읽고 순서를 파악할 수 있다.' },
        { skill: 'speaking', statement: '자기 하루 일과를 시간과 함께 세 가지 이상 말할 수 있다.' },
        { skill: 'speaking', statement: '몇 시에 무엇을 하는지 묻고 답할 수 있다.' },
        { skill: 'writing', statement: 'I get up at seven. 같은 시각 표현 문장을 쓸 수 있다.' },
        { skill: 'writing', statement: '자기 하루를 네 문장으로 순서대로 쓸 수 있다.' },
      ],
    },

    {
      order: 12,
      title: 'Can You?',
      titleKo: '할 수 있는 것',
      theme: '능력',
      grammar: [
        { title: 'can / can’t', canDo: '할 수 있는 일과 없는 일을 말할 수 있다.' },
        { title: 'Can you ~? 의문문', canDo: '상대가 할 수 있는지 물을 수 있다.' },
      ],
      vocabulary: [
        { en: 'can', ko: '~할 수 있다', pos: 'verb' },
        { en: 'swim', ko: '수영하다', pos: 'verb' },
        { en: 'ride', ko: '타다', pos: 'verb' },
        { en: 'sing', ko: '노래하다', pos: 'verb' },
        { en: 'dance', ko: '춤추다', pos: 'verb' },
        { en: 'draw', ko: '그리다', pos: 'verb' },
        { en: 'cook', ko: '요리하다', pos: 'verb' },
        { en: 'read', ko: '읽다', pos: 'verb' },
        { en: 'write', ko: '쓰다', pos: 'verb' },
        { en: 'speak', ko: '말하다', pos: 'verb' },
        { en: 'help', ko: '돕다', pos: 'verb' },
        { en: 'try', ko: '해 보다', pos: 'verb' },
        { en: 'well', ko: '잘', pos: 'adverb' },
        { en: 'again', ko: '다시', pos: 'adverb' },
        { en: 'together', ko: '함께', pos: 'adverb' },
        { en: 'English', ko: '영어', pos: 'noun' },
        { en: 'Korean', ko: '한국어', pos: 'noun' },
        { en: 'bike', ko: '자전거', pos: 'noun' },
        { en: 'song', ko: '노래', pos: 'noun' },
        { en: 'game', ko: '놀이, 게임', pos: 'noun' },
      ],
      canDo: [
        { skill: 'listening', statement: 'can 과 can’t 를 듣고 구별할 수 있다.' },
        { skill: 'listening', statement: '누가 무엇을 할 수 있는지 듣고 표에 표시할 수 있다.' },
        { skill: 'reading', statement: 'can 문장을 읽고 가능한지 아닌지 판단할 수 있다.' },
        { skill: 'reading', statement: '인물 소개 글을 읽고 그 사람이 할 수 있는 일을 찾을 수 있다.' },
        { skill: 'speaking', statement: '자기가 할 수 있는 것과 할 수 없는 것을 말할 수 있다.' },
        { skill: 'speaking', statement: 'Can you ~? 로 묻고 답할 수 있다.' },
        { skill: 'writing', statement: 'can 과 can’t 문장을 구별해 쓸 수 있다.' },
        { skill: 'writing', statement: '자기가 할 수 있는 일 세 가지를 문장으로 쓸 수 있다.' },
      ],
    },

    {
      order: 13,
      title: 'My Friends',
      titleKo: '내 친구',
      theme: '관계',
      grammar: [
        { title: '3인칭 단수 현재형 (He likes / She has)', canDo: '제3자의 행동과 취향을 말할 수 있다.' },
        { title: '인물 묘사 형용사', canDo: '사람의 성격을 말할 수 있다.' },
      ],
      vocabulary: [
        { en: 'friend', ko: '친구', pos: 'noun' },
        { en: 'classmate', ko: '반 친구', pos: 'noun' },
        { en: 'boy', ko: '소년', pos: 'noun' },
        { en: 'girl', ko: '소녀', pos: 'noun' },
        { en: 'party', ko: '파티', pos: 'noun' },
        { en: 'gift', ko: '선물', pos: 'noun' },
        { en: 'funny', ko: '재미있는', pos: 'adjective' },
        { en: 'smart', ko: '똑똑한', pos: 'adjective' },
        { en: 'quiet', ko: '조용한', pos: 'adjective' },
        { en: 'best', ko: '가장 좋은', pos: 'adjective' },
        { en: 'happy', ko: '행복한', pos: 'adjective' },
        { en: 'sad', ko: '슬픈', pos: 'adjective' },
        { en: 'same', ko: '같은', pos: 'adjective' },
        { en: 'different', ko: '다른', pos: 'adjective' },
        { en: 'favorite', ko: '가장 좋아하는', pos: 'adjective' },
        { en: 'know', ko: '알다', pos: 'verb' },
        { en: 'talk', ko: '이야기하다', pos: 'verb' },
        { en: 'laugh', ko: '웃다', pos: 'verb' },
        { en: 'share', ko: '나누다', pos: 'verb' },
        { en: 'always', ko: '항상', pos: 'adverb' },
        { en: 'sometimes', ko: '가끔', pos: 'adverb' },
      ],
      canDo: [
        { skill: 'listening', statement: '친구를 소개하는 말을 듣고 그 친구의 특징을 파악할 수 있다.' },
        { skill: 'listening', statement: 'He 와 She 를 듣고 누구를 가리키는지 알 수 있다.' },
        { skill: 'reading', statement: '친구 소개 글을 읽고 인물의 특징을 정리할 수 있다.' },
        { skill: 'reading', statement: '3인칭 단수 문장을 읽고 누구에 대한 이야기인지 찾을 수 있다.' },
        { skill: 'speaking', statement: '친구를 이름·나이·좋아하는 것과 함께 소개할 수 있다.' },
        { skill: 'speaking', statement: 'He likes ~ / She has ~ 형태로 말할 수 있다.' },
        { skill: 'writing', statement: '3인칭 단수에 -s 를 붙여 문장을 쓸 수 있다.' },
        { skill: 'writing', statement: '친구를 소개하는 문장 네 개를 쓸 수 있다.' },
      ],
    },

    {
      order: 14,
      title: 'About Me',
      titleKo: '나를 소개해요',
      theme: '통합·발표',
      isReview: true,
      grammar: [{ title: '1–13단원 통합' }],
      vocabulary: [],
      canDo: [
        { skill: 'listening', statement: '또래의 자기소개 발표를 듣고 핵심 정보를 파악할 수 있다.' },
        { skill: 'listening', statement: '발표를 듣고 그 사람에게 물어볼 질문 한 가지를 만들 수 있다.' },
        { skill: 'reading', statement: '자기소개 글을 읽고 인물 정보를 표로 정리할 수 있다.' },
        { skill: 'reading', statement: '여러 사람의 소개 글을 읽고 공통점을 찾을 수 있다.' },
        { skill: 'speaking', statement: '자기소개를 이어진 3–4문장으로 할 수 있다.' },
        { skill: 'speaking', statement: '발표 후 간단한 질문에 답할 수 있다.' },
        { skill: 'writing', statement: '자기소개 글을 다섯 문장 이상으로 쓸 수 있다.' },
        { skill: 'writing', statement: '대문자·마침표·띄어쓰기를 지켜 글을 쓸 수 있다.' },
      ],
    },
  ],
}

/** 지금까지 원안이 작성된 레벨 */
export const SEED_LEVELS = [A1_1]

export function seedFor(levelCode: string) {
  return SEED_LEVELS.find((l) => l.levelCode === levelCode)
}
