-- A1.1 교육과정 원안 적재
--
-- lib/seed/a1-1.ts 에서 생성된 SQL 입니다.
-- 이 파일을 직접 고치지 말고 원본 TS 를 고친 뒤 다시 생성하세요.
--
-- 사전 조건: docs/tables.sql 로 units · can_do_statements · grammar_points ·
--            lexical_items 테이블이 만들어져 있어야 합니다.
--
-- 두 번 실행하면 중복 적재됩니다. 한 번만 실행하세요.

begin;

-- 1. 단원 14개
insert into app_6.units
  (level_code, order_index, title, title_ko, theme, weeks, overview, is_published)
values
  ('A1.1', 1, 'Hello!', '인사와 이름', '만남', 1, '문법: be동사 (I am / You are), 인칭대명사 주격 I · you, 알파벳 대소문자
신규 어휘 12개', true),
  ('A1.1', 2, 'Numbers & Age', '숫자와 나이', '나', 1, '문법: 숫자 1–20, How old are you? / I am ~ years old
신규 어휘 13개', true),
  ('A1.1', 3, 'My Family', '우리 가족', '가족', 1, '문법: this / that, 소유격 my · your · his · her, be동사 3인칭 (He is / She is)
신규 어휘 14개', true),
  ('A1.1', 4, 'My Things', '내 물건', '사물', 1, '문법: 명사 복수형, 관사 a / an, What’s this? / It’s a ~
신규 어휘 15개', true),
  ('A1.1', 5, 'Colors & Shapes', '색깔과 모양', '묘사', 1, '문법: 형용사 + 명사 어순, It is + 형용사
신규 어휘 16개', true),
  ('A1.1', 6, 'My Classroom', '우리 교실', '학교', 1, '문법: There is / There are, some / many
신규 어휘 17개', true),
  ('A1.1', 7, 'Review 1', '중간 통합', '복습·점검', 1, '문법: 1–6단원 통합
통합·복습 단원 (신규 어휘 없음)', true),
  ('A1.1', 8, 'Where Is It?', '어디에 있나요', '위치', 1, '문법: 장소 전치사 in / on / under / next to, Where is ~?
신규 어휘 17개', true),
  ('A1.1', 9, 'Food I Like', '좋아하는 음식', '음식', 1, '문법: 일반동사 현재형 긍정 (I like ~), 일반동사 부정 (I don’t like ~)
신규 어휘 18개', true),
  ('A1.1', 10, 'Animals', '동물', '동물', 1, '문법: 일반동사 의문문 (Do you like ~?), Yes, I do. / No, I don’t.
신규 어휘 18개', true),
  ('A1.1', 11, 'My Day', '하루 일과', '일상', 1, '문법: 현재시제 일과 표현, 시각 말하기 (at seven / o’clock), 시간 전치사 at
신규 어휘 19개', true),
  ('A1.1', 12, 'Can You?', '할 수 있는 것', '능력', 1, '문법: can / can’t, Can you ~? 의문문
신규 어휘 20개', true),
  ('A1.1', 13, 'My Friends', '내 친구', '관계', 1, '문법: 3인칭 단수 현재형 (He likes / She has), 인물 묘사 형용사
신규 어휘 21개', true),
  ('A1.1', 14, 'About Me', '나를 소개해요', '통합·발표', 1, '문법: 1–13단원 통합
통합·복습 단원 (신규 어휘 없음)', true);

-- 2. 성취기준
insert into app_6.can_do_statements (unit_id, skill, statement_ko, order_index)
select u.id, v.skill, v.statement, v.ord
from (values
  (1, 'listening', '아침·점심·저녁 인사말을 듣고 언제 쓰는 인사인지 구별할 수 있다.', 1),
  (1, 'listening', '상대가 또박또박 말하는 이름의 철자를 듣고 받아 적을 수 있다.', 2),
  (1, 'reading', '이름표에 적힌 이름을 소리 내어 읽을 수 있다.', 3),
  (1, 'reading', '인사말이 적힌 문장을 읽고 알맞은 상황 그림과 연결할 수 있다.', 4),
  (1, 'speaking', '시간대에 맞는 인사말로 먼저 인사할 수 있다.', 5),
  (1, 'speaking', '이름을 묻고 답할 수 있다. (What’s your name? — My name is ~)', 6),
  (1, 'writing', '자기 이름을 알파벳 대소문자로 바르게 쓸 수 있다.', 7),
  (1, 'writing', 'My name is ~ 문장을 첫 글자 대문자와 마침표를 지켜 쓸 수 있다.', 8),
  (2, 'listening', '1–20 사이의 숫자를 듣고 아라비아 숫자로 받아 적을 수 있다.', 1),
  (2, 'listening', '나이를 말하는 문장을 듣고 몇 살인지 알 수 있다.', 2),
  (2, 'reading', '숫자 단어(one, two …)를 읽고 아라비아 숫자와 연결할 수 있다.', 3),
  (2, 'reading', '이름과 나이가 적힌 소개 카드를 읽고 정보를 찾을 수 있다.', 4),
  (2, 'speaking', '나이를 묻고 답할 수 있다.', 5),
  (2, 'speaking', '전화번호를 한 자리씩 또박또박 말할 수 있다.', 6),
  (2, 'writing', '1–20을 영어 단어로 쓸 수 있다.', 7),
  (2, 'writing', 'I am ~ years old. 문장을 쓸 수 있다.', 8),
  (3, 'listening', '가족 호칭을 듣고 가계도에서 해당 인물을 찾을 수 있다.', 1),
  (3, 'listening', '가족을 소개하는 말을 듣고 가족이 몇 명인지 셀 수 있다.', 2),
  (3, 'reading', '가족 소개 글을 읽고 인물과 관계를 연결할 수 있다.', 3),
  (3, 'reading', 'his 와 her 를 구별해 누구의 것인지 파악할 수 있다.', 4),
  (3, 'speaking', '사진을 보며 This is my ~ 로 가족을 소개할 수 있다.', 5),
  (3, 'speaking', '가족 구성원을 세 명 이상 이어서 소개할 수 있다.', 6),
  (3, 'writing', 'He is / She is 를 구별해 가족 소개 문장을 쓸 수 있다.', 7),
  (3, 'writing', '가족을 소개하는 문장 세 개를 이어서 쓸 수 있다.', 8),
  (4, 'listening', '물건 이름을 듣고 여러 그림 중에서 고를 수 있다.', 1),
  (4, 'listening', '단수와 복수를 듣고 한 개인지 여러 개인지 구별할 수 있다.', 2),
  (4, 'reading', '물건 목록을 읽고 각각 몇 개인지 파악할 수 있다.', 3),
  (4, 'reading', 'a 와 an 이 알맞게 쓰였는지 찾아낼 수 있다.', 4),
  (4, 'speaking', '물건을 가리키며 What’s this? 로 묻고 답할 수 있다.', 5),
  (4, 'speaking', '자기 가방 속 물건을 세 가지 이상 말할 수 있다.', 6),
  (4, 'writing', '명사의 복수형을 규칙에 맞게 쓸 수 있다.', 7),
  (4, 'writing', 'It’s a ~ / They are ~ 문장을 구별해 쓸 수 있다.', 8),
  (5, 'listening', '색깔 이름을 듣고 해당 색을 고를 수 있다.', 1),
  (5, 'listening', '색과 크기를 함께 설명하는 말을 듣고 알맞은 그림을 찾을 수 있다.', 2),
  (5, 'reading', '색깔·모양 단어를 읽고 그림과 연결할 수 있다.', 3),
  (5, 'reading', '사물을 묘사한 짧은 문장을 읽고 알맞은 그림을 고를 수 있다.', 4),
  (5, 'speaking', '사물의 색과 크기를 함께 말할 수 있다. (It’s a big red ball.)', 5),
  (5, 'speaking', '좋아하는 색을 말하고 그 색의 물건을 하나 들 수 있다.', 6),
  (5, 'writing', '형용사와 명사의 순서를 지켜 문장을 쓸 수 있다.', 7),
  (5, 'writing', '사물 두 개를 색과 크기로 묘사하는 문장을 쓸 수 있다.', 8),
  (6, 'listening', '교실 사물의 이름을 듣고 교실에서 찾을 수 있다.', 1),
  (6, 'listening', 'There is 와 There are 를 듣고 하나인지 여럿인지 구별할 수 있다.', 2),
  (6, 'reading', '교실을 설명한 글을 읽고 없는 물건을 찾아낼 수 있다.', 3),
  (6, 'reading', 'There is/are 문장을 읽고 사물의 개수를 파악할 수 있다.', 4),
  (6, 'speaking', '교실에 무엇이 있는지 There is/are 로 말할 수 있다.', 5),
  (6, 'speaking', '교실 사물 다섯 가지를 이어서 말할 수 있다.', 6),
  (6, 'writing', 'There is 와 There are 를 구별해 쓸 수 있다.', 7),
  (6, 'writing', '교실을 설명하는 문장 세 개를 쓸 수 있다.', 8),
  (7, 'listening', '1–6단원 표현이 섞인 짧은 대화를 듣고 이름·나이·물건을 파악할 수 있다.', 1),
  (7, 'listening', '들은 정보를 표에 나누어 정리할 수 있다.', 2),
  (7, 'reading', '배운 어휘로 쓰인 짧은 소개 글을 읽고 내용을 파악할 수 있다.', 3),
  (7, 'reading', '글을 읽고 주어진 문장의 참·거짓을 판단할 수 있다.', 4),
  (7, 'speaking', '이름·나이·가족·물건을 섞어 자기를 소개할 수 있다.', 5),
  (7, 'speaking', '짝에게 배운 표현으로 세 가지 이상 질문할 수 있다.', 6),
  (7, 'writing', '배운 문형으로 자기소개 문장 다섯 개를 쓸 수 있다.', 7),
  (7, 'writing', '첫 글자 대문자와 마침표를 지켜 쓸 수 있다.', 8),
  (8, 'listening', '위치를 설명하는 말을 듣고 물건을 찾을 수 있다.', 1),
  (8, 'listening', '전치사를 듣고 알맞은 위치의 그림을 고를 수 있다.', 2),
  (8, 'reading', '위치를 나타낸 문장을 읽고 그림과 연결할 수 있다.', 3),
  (8, 'reading', '방을 설명한 글을 읽고 각 물건이 어디 있는지 파악할 수 있다.', 4),
  (8, 'speaking', '물건의 위치를 묻고 답할 수 있다.', 5),
  (8, 'speaking', '자기 방에 무엇이 어디 있는지 세 가지 이상 말할 수 있다.', 6),
  (8, 'writing', '전치사를 써서 위치를 나타내는 문장을 쓸 수 있다.', 7),
  (8, 'writing', '그림을 보고 위치를 설명하는 문장 세 개를 쓸 수 있다.', 8),
  (9, 'listening', '음식 이름을 듣고 그림에서 고를 수 있다.', 1),
  (9, 'listening', '좋아함과 싫어함을 나타내는 말을 듣고 구별할 수 있다.', 2),
  (9, 'reading', '음식 이름을 읽고 종류별로 분류할 수 있다.', 3),
  (9, 'reading', '좋아하는 음식을 소개한 글에서 원하는 정보를 찾을 수 있다.', 4),
  (9, 'speaking', '좋아하는 음식과 싫어하는 음식을 말할 수 있다.', 5),
  (9, 'speaking', '짝에게 좋아하는 음식을 묻고 답할 수 있다.', 6),
  (9, 'writing', 'I like / I don’t like 문장을 쓸 수 있다.', 7),
  (9, 'writing', '좋아하는 음식 세 가지를 문장으로 쓸 수 있다.', 8),
  (10, 'listening', '동물 이름을 듣고 그림에서 고를 수 있다.', 1),
  (10, 'listening', 'Do you like ~? 질문과 대답을 듣고 좋아하는지 알 수 있다.', 2),
  (10, 'reading', '동물을 묘사한 짧은 글을 읽고 어떤 동물인지 맞힐 수 있다.', 3),
  (10, 'reading', '질문과 대답을 읽고 알맞게 짝지을 수 있다.', 4),
  (10, 'speaking', 'Do you like ~? 로 묻고 Yes/No 로 답할 수 있다.', 5),
  (10, 'speaking', '좋아하는 동물을 색과 크기를 넣어 소개할 수 있다.', 6),
  (10, 'writing', 'Do you like ~? 형태의 의문문을 쓸 수 있다.', 7),
  (10, 'writing', '좋아하는 동물을 소개하는 문장 세 개를 쓸 수 있다.', 8),
  (11, 'listening', '시각을 듣고 시계 그림과 연결할 수 있다.', 1),
  (11, 'listening', '하루 일과를 듣고 일어난 순서대로 정리할 수 있다.', 2),
  (11, 'reading', '일과표를 읽고 시간과 활동을 연결할 수 있다.', 3),
  (11, 'reading', '하루를 설명한 글을 읽고 순서를 파악할 수 있다.', 4),
  (11, 'speaking', '자기 하루 일과를 시간과 함께 세 가지 이상 말할 수 있다.', 5),
  (11, 'speaking', '몇 시에 무엇을 하는지 묻고 답할 수 있다.', 6),
  (11, 'writing', 'I get up at seven. 같은 시각 표현 문장을 쓸 수 있다.', 7),
  (11, 'writing', '자기 하루를 네 문장으로 순서대로 쓸 수 있다.', 8),
  (12, 'listening', 'can 과 can’t 를 듣고 구별할 수 있다.', 1),
  (12, 'listening', '누가 무엇을 할 수 있는지 듣고 표에 표시할 수 있다.', 2),
  (12, 'reading', 'can 문장을 읽고 가능한지 아닌지 판단할 수 있다.', 3),
  (12, 'reading', '인물 소개 글을 읽고 그 사람이 할 수 있는 일을 찾을 수 있다.', 4),
  (12, 'speaking', '자기가 할 수 있는 것과 할 수 없는 것을 말할 수 있다.', 5),
  (12, 'speaking', 'Can you ~? 로 묻고 답할 수 있다.', 6),
  (12, 'writing', 'can 과 can’t 문장을 구별해 쓸 수 있다.', 7),
  (12, 'writing', '자기가 할 수 있는 일 세 가지를 문장으로 쓸 수 있다.', 8),
  (13, 'listening', '친구를 소개하는 말을 듣고 그 친구의 특징을 파악할 수 있다.', 1),
  (13, 'listening', 'He 와 She 를 듣고 누구를 가리키는지 알 수 있다.', 2),
  (13, 'reading', '친구 소개 글을 읽고 인물의 특징을 정리할 수 있다.', 3),
  (13, 'reading', '3인칭 단수 문장을 읽고 누구에 대한 이야기인지 찾을 수 있다.', 4),
  (13, 'speaking', '친구를 이름·나이·좋아하는 것과 함께 소개할 수 있다.', 5),
  (13, 'speaking', 'He likes ~ / She has ~ 형태로 말할 수 있다.', 6),
  (13, 'writing', '3인칭 단수에 -s 를 붙여 문장을 쓸 수 있다.', 7),
  (13, 'writing', '친구를 소개하는 문장 네 개를 쓸 수 있다.', 8),
  (14, 'listening', '또래의 자기소개 발표를 듣고 핵심 정보를 파악할 수 있다.', 1),
  (14, 'listening', '발표를 듣고 그 사람에게 물어볼 질문 한 가지를 만들 수 있다.', 2),
  (14, 'reading', '자기소개 글을 읽고 인물 정보를 표로 정리할 수 있다.', 3),
  (14, 'reading', '여러 사람의 소개 글을 읽고 공통점을 찾을 수 있다.', 4),
  (14, 'speaking', '자기소개를 이어진 3–4문장으로 할 수 있다.', 5),
  (14, 'speaking', '발표 후 간단한 질문에 답할 수 있다.', 6),
  (14, 'writing', '자기소개 글을 다섯 문장 이상으로 쓸 수 있다.', 7),
  (14, 'writing', '대문자·마침표·띄어쓰기를 지켜 글을 쓸 수 있다.', 8)
) as v(unit_order, skill, statement, ord)
join app_6.units u
  on u.level_code = 'A1.1' and u.order_index = v.unit_order;

-- 3. 문법 항목
insert into app_6.grammar_points
  (unit_id, title, can_do, cefr_level, order_index, is_published)
select u.id, v.title, v.can_do, 'A1', v.ord, true
from (values
  (1, 'be동사 (I am / You are)', '자기를 소개하는 문장을 만들 수 있다.', 10),
  (1, '인칭대명사 주격 I · you', '나와 상대를 가리켜 말할 수 있다.', 11),
  (1, '알파벳 대소문자', '이름을 바르게 표기할 수 있다.', 12),
  (2, '숫자 1–20', '스무 개까지 수를 세어 말할 수 있다.', 20),
  (2, 'How old are you? / I am ~ years old', '나이를 묻고 답할 수 있다.', 21),
  (3, 'this / that', '가까운 것과 먼 것을 가리켜 말할 수 있다.', 30),
  (3, '소유격 my · your · his · her', '누구의 것인지 밝혀 말할 수 있다.', 31),
  (3, 'be동사 3인칭 (He is / She is)', '제3자를 소개할 수 있다.', 32),
  (4, '명사 복수형', '하나와 여럿을 구별해 말할 수 있다.', 40),
  (4, '관사 a / an', '셀 수 있는 명사 앞에 관사를 붙여 말할 수 있다.', 41),
  (4, 'What’s this? / It’s a ~', '사물의 이름을 묻고 답할 수 있다.', 42),
  (5, '형용사 + 명사 어순', '사물을 꾸며 말할 수 있다.', 50),
  (5, 'It is + 형용사', '사물의 성질을 말할 수 있다.', 51),
  (6, 'There is / There are', '무엇이 있는지 말할 수 있다.', 60),
  (6, 'some / many', '막연한 수량을 말할 수 있다.', 61),
  (7, '1–6단원 통합', null, 70),
  (8, '장소 전치사 in / on / under / next to', '위치를 나타내어 말할 수 있다.', 80),
  (8, 'Where is ~?', '물건이 어디 있는지 물을 수 있다.', 81),
  (9, '일반동사 현재형 긍정 (I like ~)', '좋아하는 것을 말할 수 있다.', 90),
  (9, '일반동사 부정 (I don’t like ~)', '싫어하는 것을 말할 수 있다.', 91),
  (10, '일반동사 의문문 (Do you like ~?)', '상대의 취향을 물을 수 있다.', 100),
  (10, 'Yes, I do. / No, I don’t.', '짧은 대답으로 응답할 수 있다.', 101),
  (11, '현재시제 일과 표현', '반복되는 일상을 말할 수 있다.', 110),
  (11, '시각 말하기 (at seven / o’clock)', '몇 시에 하는지 말할 수 있다.', 111),
  (11, '시간 전치사 at', '시각을 문장에 넣을 수 있다.', 112),
  (12, 'can / can’t', '할 수 있는 일과 없는 일을 말할 수 있다.', 120),
  (12, 'Can you ~? 의문문', '상대가 할 수 있는지 물을 수 있다.', 121),
  (13, '3인칭 단수 현재형 (He likes / She has)', '제3자의 행동과 취향을 말할 수 있다.', 130),
  (13, '인물 묘사 형용사', '사람의 성격을 말할 수 있다.', 131),
  (14, '1–13단원 통합', null, 140)
) as v(unit_order, title, can_do, ord)
join app_6.units u
  on u.level_code = 'A1.1' and u.order_index = v.unit_order;

-- 4. 어휘
insert into app_6.lexical_items
  (unit_id, headword, meaning_ko, pos, item_type, cefr_level, is_published)
select u.id, v.headword, v.meaning_ko, v.pos, v.item_type, 'A1', true
from (values
  (1, 'hello', '안녕하세요', 'phrase', 'idiom'),
  (1, 'hi', '안녕', 'phrase', 'idiom'),
  (1, 'good morning', '좋은 아침', 'phrase', 'collocation'),
  (1, 'good afternoon', '안녕하세요 (오후 인사)', 'phrase', 'collocation'),
  (1, 'good evening', '안녕하세요 (저녁 인사)', 'phrase', 'collocation'),
  (1, 'goodbye', '안녕히 가세요', 'phrase', 'idiom'),
  (1, 'name', '이름', 'noun', 'word'),
  (1, 'nice', '좋은, 반가운', 'adjective', 'word'),
  (1, 'meet', '만나다', 'verb', 'word'),
  (1, 'teacher', '선생님', 'noun', 'word'),
  (1, 'student', '학생', 'noun', 'word'),
  (1, 'please', '부탁합니다', 'adverb', 'word'),
  (2, 'one', '하나', 'noun', 'word'),
  (2, 'two', '둘', 'noun', 'word'),
  (2, 'three', '셋', 'noun', 'word'),
  (2, 'four', '넷', 'noun', 'word'),
  (2, 'five', '다섯', 'noun', 'word'),
  (2, 'six', '여섯', 'noun', 'word'),
  (2, 'seven', '일곱', 'noun', 'word'),
  (2, 'eight', '여덟', 'noun', 'word'),
  (2, 'nine', '아홉', 'noun', 'word'),
  (2, 'ten', '열', 'noun', 'word'),
  (2, 'old', '나이가 ~인, 오래된', 'adjective', 'word'),
  (2, 'year', '해, 년', 'noun', 'word'),
  (2, 'birthday', '생일', 'noun', 'word'),
  (3, 'father', '아버지', 'noun', 'word'),
  (3, 'mother', '어머니', 'noun', 'word'),
  (3, 'brother', '형, 오빠, 남동생', 'noun', 'word'),
  (3, 'sister', '누나, 언니, 여동생', 'noun', 'word'),
  (3, 'grandfather', '할아버지', 'noun', 'word'),
  (3, 'grandmother', '할머니', 'noun', 'word'),
  (3, 'parents', '부모님', 'noun', 'word'),
  (3, 'family', '가족', 'noun', 'word'),
  (3, 'baby', '아기', 'noun', 'word'),
  (3, 'tall', '키가 큰', 'adjective', 'word'),
  (3, 'kind', '친절한', 'adjective', 'word'),
  (3, 'this', '이것, 이 사람', 'pronoun', 'word'),
  (3, 'that', '저것, 저 사람', 'pronoun', 'word'),
  (3, 'love', '사랑하다', 'verb', 'word'),
  (4, 'pen', '펜', 'noun', 'word'),
  (4, 'pencil', '연필', 'noun', 'word'),
  (4, 'book', '책', 'noun', 'word'),
  (4, 'notebook', '공책', 'noun', 'word'),
  (4, 'eraser', '지우개', 'noun', 'word'),
  (4, 'ruler', '자', 'noun', 'word'),
  (4, 'bag', '가방', 'noun', 'word'),
  (4, 'desk', '책상', 'noun', 'word'),
  (4, 'chair', '의자', 'noun', 'word'),
  (4, 'key', '열쇠', 'noun', 'word'),
  (4, 'cup', '컵', 'noun', 'word'),
  (4, 'box', '상자', 'noun', 'word'),
  (4, 'thing', '물건, 것', 'noun', 'word'),
  (4, 'have', '가지다', 'verb', 'word'),
  (4, 'my', '나의', 'determiner', 'word'),
  (5, 'red', '빨강', 'adjective', 'word'),
  (5, 'blue', '파랑', 'adjective', 'word'),
  (5, 'yellow', '노랑', 'adjective', 'word'),
  (5, 'green', '초록', 'adjective', 'word'),
  (5, 'black', '검정', 'adjective', 'word'),
  (5, 'white', '하양', 'adjective', 'word'),
  (5, 'orange', '주황', 'adjective', 'word'),
  (5, 'pink', '분홍', 'adjective', 'word'),
  (5, 'brown', '갈색', 'adjective', 'word'),
  (5, 'circle', '원', 'noun', 'word'),
  (5, 'square', '정사각형', 'noun', 'word'),
  (5, 'triangle', '삼각형', 'noun', 'word'),
  (5, 'big', '큰', 'adjective', 'word'),
  (5, 'small', '작은', 'adjective', 'word'),
  (5, 'long', '긴', 'adjective', 'word'),
  (5, 'color', '색깔', 'noun', 'word'),
  (6, 'classroom', '교실', 'noun', 'word'),
  (6, 'board', '칠판', 'noun', 'word'),
  (6, 'window', '창문', 'noun', 'word'),
  (6, 'door', '문', 'noun', 'word'),
  (6, 'clock', '시계', 'noun', 'word'),
  (6, 'map', '지도', 'noun', 'word'),
  (6, 'picture', '그림, 사진', 'noun', 'word'),
  (6, 'computer', '컴퓨터', 'noun', 'word'),
  (6, 'wall', '벽', 'noun', 'word'),
  (6, 'floor', '바닥', 'noun', 'word'),
  (6, 'light', '전등, 빛', 'noun', 'word'),
  (6, 'school', '학교', 'noun', 'word'),
  (6, 'class', '반, 수업', 'noun', 'word'),
  (6, 'many', '많은', 'determiner', 'word'),
  (6, 'some', '몇몇의', 'determiner', 'word'),
  (6, 'there', '거기에', 'adverb', 'word'),
  (6, 'new', '새로운', 'adjective', 'word'),
  (8, 'in', '~ 안에', 'preposition', 'word'),
  (8, 'on', '~ 위에', 'preposition', 'word'),
  (8, 'under', '~ 아래에', 'preposition', 'word'),
  (8, 'next to', '~ 옆에', 'preposition', 'collocation'),
  (8, 'behind', '~ 뒤에', 'preposition', 'word'),
  (8, 'in front of', '~ 앞에', 'preposition', 'collocation'),
  (8, 'room', '방', 'noun', 'word'),
  (8, 'table', '탁자', 'noun', 'word'),
  (8, 'bed', '침대', 'noun', 'word'),
  (8, 'sofa', '소파', 'noun', 'word'),
  (8, 'kitchen', '부엌', 'noun', 'word'),
  (8, 'house', '집', 'noun', 'word'),
  (8, 'where', '어디에', 'adverb', 'word'),
  (8, 'here', '여기에', 'adverb', 'word'),
  (8, 'put', '놓다', 'verb', 'word'),
  (8, 'find', '찾다', 'verb', 'word'),
  (8, 'look', '보다', 'verb', 'word'),
  (9, 'rice', '밥, 쌀', 'noun', 'word'),
  (9, 'bread', '빵', 'noun', 'word'),
  (9, 'milk', '우유', 'noun', 'word'),
  (9, 'water', '물', 'noun', 'word'),
  (9, 'juice', '주스', 'noun', 'word'),
  (9, 'apple', '사과', 'noun', 'word'),
  (9, 'banana', '바나나', 'noun', 'word'),
  (9, 'egg', '달걀', 'noun', 'word'),
  (9, 'meat', '고기', 'noun', 'word'),
  (9, 'fish', '생선', 'noun', 'word'),
  (9, 'soup', '국, 수프', 'noun', 'word'),
  (9, 'cake', '케이크', 'noun', 'word'),
  (9, 'food', '음식', 'noun', 'word'),
  (9, 'eat', '먹다', 'verb', 'word'),
  (9, 'drink', '마시다', 'verb', 'word'),
  (9, 'like', '좋아하다', 'verb', 'word'),
  (9, 'want', '원하다', 'verb', 'word'),
  (9, 'hungry', '배고픈', 'adjective', 'word'),
  (10, 'dog', '개', 'noun', 'word'),
  (10, 'cat', '고양이', 'noun', 'word'),
  (10, 'bird', '새', 'noun', 'word'),
  (10, 'rabbit', '토끼', 'noun', 'word'),
  (10, 'horse', '말', 'noun', 'word'),
  (10, 'cow', '소', 'noun', 'word'),
  (10, 'pig', '돼지', 'noun', 'word'),
  (10, 'lion', '사자', 'noun', 'word'),
  (10, 'tiger', '호랑이', 'noun', 'word'),
  (10, 'elephant', '코끼리', 'noun', 'word'),
  (10, 'monkey', '원숭이', 'noun', 'word'),
  (10, 'animal', '동물', 'noun', 'word'),
  (10, 'pet', '반려동물', 'noun', 'word'),
  (10, 'tail', '꼬리', 'noun', 'word'),
  (10, 'run', '달리다', 'verb', 'word'),
  (10, 'jump', '뛰다', 'verb', 'word'),
  (10, 'fly', '날다', 'verb', 'word'),
  (10, 'cute', '귀여운', 'adjective', 'word'),
  (11, 'get up', '일어나다', 'verb', 'phrasal_verb'),
  (11, 'wash', '씻다', 'verb', 'word'),
  (11, 'go', '가다', 'verb', 'word'),
  (11, 'come', '오다', 'verb', 'word'),
  (11, 'study', '공부하다', 'verb', 'word'),
  (11, 'play', '놀다', 'verb', 'word'),
  (11, 'sleep', '자다', 'verb', 'word'),
  (11, 'morning', '아침', 'noun', 'word'),
  (11, 'afternoon', '오후', 'noun', 'word'),
  (11, 'evening', '저녁', 'noun', 'word'),
  (11, 'night', '밤', 'noun', 'word'),
  (11, 'day', '날, 하루', 'noun', 'word'),
  (11, 'time', '시간', 'noun', 'word'),
  (11, 'home', '집', 'noun', 'word'),
  (11, 'breakfast', '아침 식사', 'noun', 'word'),
  (11, 'lunch', '점심 식사', 'noun', 'word'),
  (11, 'dinner', '저녁 식사', 'noun', 'word'),
  (11, 'early', '이른, 일찍', 'adjective', 'word'),
  (11, 'late', '늦은, 늦게', 'adjective', 'word'),
  (12, 'can', '~할 수 있다', 'verb', 'word'),
  (12, 'swim', '수영하다', 'verb', 'word'),
  (12, 'ride', '타다', 'verb', 'word'),
  (12, 'sing', '노래하다', 'verb', 'word'),
  (12, 'dance', '춤추다', 'verb', 'word'),
  (12, 'draw', '그리다', 'verb', 'word'),
  (12, 'cook', '요리하다', 'verb', 'word'),
  (12, 'read', '읽다', 'verb', 'word'),
  (12, 'write', '쓰다', 'verb', 'word'),
  (12, 'speak', '말하다', 'verb', 'word'),
  (12, 'help', '돕다', 'verb', 'word'),
  (12, 'try', '해 보다', 'verb', 'word'),
  (12, 'well', '잘', 'adverb', 'word'),
  (12, 'again', '다시', 'adverb', 'word'),
  (12, 'together', '함께', 'adverb', 'word'),
  (12, 'English', '영어', 'noun', 'word'),
  (12, 'Korean', '한국어', 'noun', 'word'),
  (12, 'bike', '자전거', 'noun', 'word'),
  (12, 'song', '노래', 'noun', 'word'),
  (12, 'game', '놀이, 게임', 'noun', 'word'),
  (13, 'friend', '친구', 'noun', 'word'),
  (13, 'classmate', '반 친구', 'noun', 'word'),
  (13, 'boy', '소년', 'noun', 'word'),
  (13, 'girl', '소녀', 'noun', 'word'),
  (13, 'party', '파티', 'noun', 'word'),
  (13, 'gift', '선물', 'noun', 'word'),
  (13, 'funny', '재미있는', 'adjective', 'word'),
  (13, 'smart', '똑똑한', 'adjective', 'word'),
  (13, 'quiet', '조용한', 'adjective', 'word'),
  (13, 'best', '가장 좋은', 'adjective', 'word'),
  (13, 'happy', '행복한', 'adjective', 'word'),
  (13, 'sad', '슬픈', 'adjective', 'word'),
  (13, 'same', '같은', 'adjective', 'word'),
  (13, 'different', '다른', 'adjective', 'word'),
  (13, 'favorite', '가장 좋아하는', 'adjective', 'word'),
  (13, 'know', '알다', 'verb', 'word'),
  (13, 'talk', '이야기하다', 'verb', 'word'),
  (13, 'laugh', '웃다', 'verb', 'word'),
  (13, 'share', '나누다', 'verb', 'word'),
  (13, 'always', '항상', 'adverb', 'word'),
  (13, 'sometimes', '가끔', 'adverb', 'word')
) as v(unit_order, headword, meaning_ko, pos, item_type)
join app_6.units u
  on u.level_code = 'A1.1' and u.order_index = v.unit_order;

commit;
